using Content.Client.Administration.UI.CustomControls;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client._Crescent.Administration.UI.PutPlayerInBody;

[GenerateTypedNameReferences]
public sealed partial class PutPlayerInBodyWindow : FancyWindow
{
    public event Action<NetUserId>? OnPlayerChosen;

    private PlayerInfo? _selected;

    public PutPlayerInBodyWindow()
    {
        RobustXamlLoader.Load(this);

        PlayerList.OnSelectionChanged += info =>
        {
            _selected = info;
            ConfirmButton.Disabled = info == null;
        };

        ConfirmButton.OnPressed += _ =>
        {
            if (_selected != null)
                OnPlayerChosen?.Invoke(_selected.SessionId);
        };
    }

    public void SetTarget(string bodyName, string? occupant)
    {
        BodyLabel.Text = Loc.GetString("put-player-in-body-body-label", ("body", bodyName));

        OccupantLabel.Visible = occupant != null;
        if (occupant != null)
            OccupantLabel.Text = Loc.GetString("put-player-in-body-occupant-label", ("player", occupant));
    }
}
