using System.Linq;
using System.Numerics;
using Content.Client.Parallax; // Frontier: Parallax control for the background
using Content.Client.Research;
using Content.Client.UserInterface.Controls;
using Content.Shared._Goobstation.Research;
using Content.Shared.Access.Systems;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Goobstation.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleMenu : FancyWindow
{
    public Action<string>? OnTechnologyCardPressed;
    public Action? OnServerButtonPressed;

    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IResourceCache _resource = default!;

    private readonly ResearchSystem _research;
    private readonly SpriteSystem _sprite;
    private readonly AccessReaderSystem _accessReader;

    /// <summary>
    /// Console entity
    /// </summary>
    public EntityUid Entity;

    /// <summary>
    /// Currently selected tech
    /// Exists for better UI refreshing
    /// </summary>
    public ProtoId<TechnologyPrototype>? CurrentTech;

    /// <summary>
    /// All technologies and their availability
    /// </summary>
    public Dictionary<string, ResearchAvailability> List = new();

    /// <summary>
    /// Cached research points
    /// </summary>
    public int Points = 0;

    /// <summary>
    /// Current server-side research cost multiplier.
    /// </summary>
    public float SoftCapMultiplier { get; private set; } = 1;

    /// <summary>
    /// Is tech currently being dragged
    /// </summary>
    private bool _draggin;

    /// <summary>
    /// Global position that all tech relates to.
    /// For dragging mostly
    /// </summary>
    private Vector2 _position = DefaultPosition;

    /// <summary>
    /// Captures the initial position to use with recenter button
    /// </summary>
    private Vector2 _initialViewPosition = DefaultPosition;

    /// <summary>
    /// Current zoom of the tree view. 1 is the authored size.
    /// </summary>
    private float _zoom = 1f;

    /// <summary>
    /// Grid coordinates of every control inside <see cref="DragContainer"/>, so the view can be
    /// rebuilt on pan and zoom without recreating the controls.
    /// </summary>
    private readonly Dictionary<Control, Vector2i> _gridPositions = new();

    /// <summary>
    /// Fonts used by the tree headers, keyed by pixel size.
    /// </summary>
    private readonly Dictionary<int, Font> _headerFonts = new();

    /// <summary>
    /// Base spacing for the compact overview layout.
    /// </summary>
    private const int GridSize = 60;

    private const float MinZoom = 0.4f;

    private const float MaxZoom = 1.75f;

    /// <summary>
    /// Multiplicative zoom applied per button press or wheel notch.
    /// </summary>
    private const float ZoomStep = 1.1f;

    private const int MaxRowsPerLayer = 6;

    private const int LayerColumnStride = 2;

    private const int TechnologyColumnStart = 2;

    private static readonly HashSet<string> FactionDisciplines = new(StringComparer.Ordinal)
    {
        "Minutemen",
        "Interdyne",
        "Cyberdawn",
        "Coalition",
        "Imperial",
        "Communard",
        "Corporate",
        "Families",
    };

    private static readonly Dictionary<string, int> CivilianDisciplineOrder = new(StringComparer.Ordinal)
    {
        ["Mechatronics"] = 0,
        ["Electronics"] = 1,
        ["Astronautics"] = 2,
        ["Biochemical"] = 3,
    };

    /// <summary>
    /// Initial pan offset. The compact nodes and wider graph pane provide a more zoomed-out view.
    /// </summary>
    private static readonly Vector2i DefaultPosition = new(20, 14);

    private ParallaxControl _parallaxControl; // Frontier: Parallax control for the background

    public FancyResearchConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _research = _entity.System<ResearchSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _accessReader = _entity.System<AccessReaderSystem>();

        // Frontier: Initialize parallax background
        _parallaxControl = new ParallaxControl
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        // Add the parallax control to the ResearchesContainer at the beginning (bottom layer)
        ResearchesContainer.AddChild(_parallaxControl);

        // Set the proper rendering order by adjusting positions in the parent's child list
        // Controls with a higher position value are drawn on top (foreground)
        // Make sure the parallax is at the bottom of the z-order (drawn first)
        _parallaxControl.SetPositionInParent(0);

        // The drag container should be in the middle
        DragContainer.SetPositionInParent(1);

        // The view controls should be at the top of the z-order (drawn last)
        ViewControls.SetPositionInParent(2);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        DragContainer.OnKeyBindDown += OnKeybindDown;
        DragContainer.OnKeyBindUp += OnKeybindUp;
        DragContainer.WheelScrolled += OnGraphScrolled;
        RecenterButton.OnPressed += _ => Recenter();
        ZoomInButton.OnPressed += _ => SetZoom(_zoom * ZoomStep);
        ZoomOutButton.OnPressed += _ => SetZoom(_zoom / ZoomStep);

        // Empty initialization
        UpdatePanels(List);
    }

    public void SetEntity(EntityUid entity)
        => Entity = entity;

    public void UpdatePanels(Dictionary<string, ResearchAvailability> dict)
    {
        DragContainer.RemoveAllChildren();
        _gridPositions.Clear();
        List = dict;

        if (CurrentTech is { } current && !List.ContainsKey(current))
        {
            CurrentTech = null;
            InfoContainer.RemoveAllChildren();
        }

        var technologies = List.Keys
            .Select(_prototype.Index<TechnologyPrototype>)
            .ToList();
        var layout = CalculateTechnologyLayout(technologies);

        foreach (var header in layout.Headers)
        {
            var control = new TreeHeaderControl(header);
            DragContainer.AddChild(control);
            _gridPositions[control] = header.Position;
        }

        foreach (var tech in List)
        {
            var proto = _prototype.Index<TechnologyPrototype>(tech.Key);

            var control = new FancyResearchConsoleItem(proto, _sprite, tech.Value);
            DragContainer.AddChild(control);

            // Positions relate to _position and are applied by ApplyView
            _gridPositions[control] = layout.Positions[proto.ID];
            control.SelectAction += SelectTech;

            if (tech.Key == CurrentTech)
                SelectTech(proto, tech.Value);
        }

        ApplyView();
        DragContainer.RebuildConnectionCache();
    }

    #region View transform
    /// <summary>
    /// Places and sizes every node according to the current pan offset and zoom.
    /// </summary>
    private void ApplyView()
    {
        DragContainer.Zoom = _zoom;

        foreach (var (control, gridPosition) in _gridPositions)
        {
            switch (control)
            {
                case FancyResearchConsoleItem item:
                    item.SetZoom(_zoom);
                    break;
                case TreeHeaderControl header:
                    header.SetZoom(_zoom, GetHeaderFont);
                    break;
            }

            LayoutContainer.SetPosition(control, _position + gridPosition * (GridSize * _zoom));
        }

        ZoomLabel.Text = Loc.GetString(
            "research-console-menu-zoom-label",
            ("percent", (int) MathF.Round(_zoom * 100)));
    }

    /// <summary>
    /// Changes the zoom while keeping whatever sits under <paramref name="anchor"/> in place.
    /// </summary>
    /// <param name="zoom">Requested zoom, clamped to the supported range.</param>
    /// <param name="anchor">Point in <see cref="DragContainer"/> space to zoom around. Defaults to the view centre.</param>
    private void SetZoom(float zoom, Vector2? anchor = null)
    {
        zoom = Math.Clamp(zoom, MinZoom, MaxZoom);
        if (MathF.Abs(zoom - _zoom) < 0.0001f)
            return;

        var pivot = anchor ?? DragContainer.Size / 2f;
        _position = pivot - (pivot - _position) * (zoom / _zoom);
        _zoom = zoom;

        ApplyView();
    }

    private void OnGraphScrolled(GUIMouseWheelEventArgs args)
        => SetZoom(_zoom * MathF.Pow(ZoomStep, args.Delta.Y), args.RelativePosition);

    private Font GetHeaderFont(int size)
    {
        if (_headerFonts.TryGetValue(size, out var font))
            return font;

        font = new VectorFont(_resource.GetResource<FontResource>("/Fonts/NotoSans/NotoSans-Regular.ttf"), size);
        _headerFonts[size] = font;
        return font;
    }
    #endregion

    /// <summary>
    /// Creates compact, labelled faction and civilian swimlanes. Each prerequisite depth
    /// gets its own horizontal band, while large bands wrap to keep the tree readable.
    /// Authored positions are still preserved and only missing positions are generated.
    /// </summary>
    private ResearchTreeLayout CalculateTechnologyLayout(
        IReadOnlyCollection<TechnologyPrototype> technologies)
    {
        var byId = technologies.ToDictionary(technology => technology.ID);
        var depthCache = new Dictionary<string, int>();

        int GetDepth(TechnologyPrototype technology, HashSet<string> visiting)
        {
            if (depthCache.TryGetValue(technology.ID, out var cached))
                return cached;

            var tierDepth = Math.Max(0, technology.Tier - 1);
            if (!visiting.Add(technology.ID))
                return tierDepth;

            var prerequisiteDepth = 0;
            foreach (var prerequisiteId in technology.TechnologyPrerequisites)
            {
                if (!byId.TryGetValue(prerequisiteId, out var prerequisite))
                    continue;

                prerequisiteDepth = Math.Max(prerequisiteDepth, GetDepth(prerequisite, visiting) + 1);
            }

            visiting.Remove(technology.ID);
            var depth = Math.Max(tierDepth, prerequisiteDepth);
            depthCache[technology.ID] = depth;
            return depth;
        }

        var positions = technologies
            .Where(technology => technology.Position.HasValue)
            .ToDictionary(technology => technology.ID, technology => technology.Position!.Value);
        var occupied = positions.Values.ToHashSet();
        var depths = technologies.ToDictionary(
            technology => technology.ID,
            technology => GetDepth(technology, new HashSet<string>()));
        var headers = new List<TreeHeaderLayout>();
        var laneTop = 0;
        bool? currentSectionIsCivilian = null;

        foreach (var discipline in technologies
                     .GroupBy(technology => technology.Discipline)
                     .OrderBy(group => FactionDisciplines.Contains(group.Key.Id) ? 0 : 1)
                     .ThenBy(group => CivilianDisciplineOrder.GetValueOrDefault(group.Key.Id, int.MaxValue))
                     .ThenBy(group => group.Key.Id))
        {
            var disciplinePrototype = _prototype.Index<TechDisciplinePrototype>(discipline.Key);
            var isCivilian = !FactionDisciplines.Contains(discipline.Key.Id);

            if (currentSectionIsCivilian != isCivilian)
            {
                var sectionName = Loc.GetString(isCivilian
                    ? "research-console-tree-section-civilian"
                    : "research-console-tree-section-faction");
                var sectionColor = isCivilian
                    ? Color.FromHex("#9eb7cf")
                    : disciplinePrototype.Color;

                headers.Add(new TreeHeaderLayout(
                    $"{sectionName.ToUpperInvariant()} · {Loc.GetString("research-console-tree-prerequisite-legend")}",
                    sectionColor,
                    new Vector2i(0, laneTop),
                    430,
                    true));
                laneTop++;
                currentSectionIsCivilian = isCivilian;
            }

            var columns = discipline
                .GroupBy(technology => depths[technology.ID])
                .OrderBy(group => group.Key)
                .ToList();
            var laneItemTop = laneTop + 1;
            var laneHeight = Math.Min(MaxRowsPerLayer, columns.Max(column => column.Count()));
            var columnOffset = 0;

            headers.Add(new TreeHeaderLayout(
                Loc.GetString(disciplinePrototype.Name),
                disciplinePrototype.Color,
                new Vector2i(0, laneTop),
                118,
                false));

            foreach (var column in columns)
            {
                var orderedTechnologies = column
                    .OrderBy(technology => GetPrerequisiteBarycenter(technology, positions))
                    .ThenBy(technology => technology.ID)
                    .ToList();
                var wrappedColumnCount = (int) Math.Ceiling(orderedTechnologies.Count / (float) MaxRowsPerLayer);
                var columnX = TechnologyColumnStart + columnOffset * LayerColumnStride;
                var minimumTier = orderedTechnologies.Min(technology => technology.Tier);
                var maximumTier = orderedTechnologies.Max(technology => technology.Tier);
                var tierLabel = minimumTier == maximumTier
                    ? Loc.GetString("research-console-tree-tier", ("tier", minimumTier))
                    : Loc.GetString(
                        "research-console-tree-tier-range",
                        ("minimum", minimumTier),
                        ("maximum", maximumTier));
                string? tierTooltip = null;

                if (minimumTier == maximumTier &&
                    minimumTier > 1 &&
                    disciplinePrototype.TierPrerequisites.TryGetValue(minimumTier, out var requiredFraction))
                {
                    var previousTier = minimumTier - 1;
                    var previousTierTechnologies = discipline
                        .Where(technology => technology.Tier == previousTier)
                        .ToList();
                    var researchedCount = previousTierTechnologies.Count(technology =>
                        List.GetValueOrDefault(technology.ID) == ResearchAvailability.Researched);
                    var requiredCount = (int) Math.Ceiling(previousTierTechnologies.Count * requiredFraction);
                    var requiredPercent = (int) MathF.Round(requiredFraction * 100f);

                    tierLabel = Loc.GetString(
                        "research-console-tree-tier-gated",
                        ("tier", minimumTier),
                        ("percent", requiredPercent));
                    tierTooltip = Loc.GetString(
                        "research-console-tree-tier-gated-tooltip",
                        ("tier", minimumTier),
                        ("previousTier", previousTier),
                        ("researched", researchedCount),
                        ("total", previousTierTechnologies.Count),
                        ("required", requiredCount),
                        ("percent", requiredPercent));
                }

                headers.Add(new TreeHeaderLayout(
                    tierLabel,
                    disciplinePrototype.Color,
                    new Vector2i(columnX, laneTop),
                    wrappedColumnCount * LayerColumnStride * GridSize - 12,
                    false,
                    tierTooltip));

                for (var index = 0; index < orderedTechnologies.Count; index++)
                {
                    var technology = orderedTechnologies[index];
                    if (technology.Position.HasValue)
                        continue;

                    var wrappedColumn = index / MaxRowsPerLayer;
                    var row = index % MaxRowsPerLayer;
                    var candidate = new Vector2i(
                        columnX + wrappedColumn * LayerColumnStride,
                        laneItemTop + row);
                    while (!occupied.Add(candidate))
                        candidate = new Vector2i(candidate.X, candidate.Y + 1);

                    positions[technology.ID] = candidate;
                }

                columnOffset += wrappedColumnCount + 1;
            }

            laneTop = laneItemTop + laneHeight + 1;
        }

        return new ResearchTreeLayout(positions, headers);

        static float GetPrerequisiteBarycenter(
            TechnologyPrototype technology,
            IReadOnlyDictionary<string, Vector2i> placedPositions)
        {
            var positionSum = 0f;
            var prerequisiteCount = 0;
            foreach (var prerequisite in technology.TechnologyPrerequisites)
            {
                if (!placedPositions.TryGetValue(prerequisite.Id, out var position))
                    continue;

                positionSum += position.Y;
                prerequisiteCount++;
            }

            return prerequisiteCount == 0 ? float.MaxValue : positionSum / prerequisiteCount;
        }
    }

    public void UpdateInformationPanel(int points, float softCapMultiplier)
    {
        SoftCapMultiplier = softCapMultiplier;
        UpdateResearchPoints(points);

        if (!_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database))
            return;

        var disciplineText = Loc.GetString("research-discipline-none");
        var disciplineColor = Color.Gray;
        if (database.MainDiscipline != null)
        {
            var mainDiscipline = _prototype.Index<TechDisciplinePrototype>(database.MainDiscipline);
            disciplineText = Loc.GetString(mainDiscipline.Name);
            disciplineColor = mainDiscipline.Color;
        }

        var disciplineMessage = new FormattedMessage();
        disciplineMessage.AddMarkupOrThrow(Loc.GetString(
            "research-console-menu-main-discipline",
            ("name", disciplineText),
            ("color", disciplineColor)));
        MainDisciplineLabel.SetMessage(disciplineMessage);

        var softcapMessage = new FormattedMessage();
        softcapMessage.AddMarkupOrThrow(Loc.GetString(
            "research-console-menu-softcap-amount-text",
            ("softcap", softCapMultiplier.ToString("0.##"))));
        SoftcapAmountLabel.SetMessage(softcapMessage);

        TierDisplayContainer.RemoveAllChildren();
        foreach (var disciplineId in database.SupportedDisciplines)
        {
            var discipline = _prototype.Index<TechDisciplinePrototype>(disciplineId);
            var tier = _research.GetHighestDisciplineTier(database, discipline);

            var texture = new TextureRect
            {
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center
            };
            var label = new RichTextLabel();
            texture.Texture = _sprite.Frame0(discipline.Icon);
            label.SetMessage(Loc.GetString("research-console-tier-info-small", ("tier", tier)));

            var control = new BoxContainer
            {
                Children =
                {
                    texture,
                    label,
                    new Control
                    {
                        MinWidth = 10
                    }
                }
            };
            TierDisplayContainer.AddChild(control);
        }
    }

    public void UpdateResearchPoints(int points)
    {
        Points = points;

        var amountMsg = new FormattedMessage();
        amountMsg.AddMarkupOrThrow(Loc.GetString("research-console-menu-research-points-text",
            ("points", points)));
        ResearchAmountLabel.SetMessage(amountMsg);
    }

    #region Drag handle
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_draggin)
            return;

        _position += args.Relative;
        ApplyView();
    }

    /// <summary>
    /// Raised when LMB is pressed at <see cref="DragContainer"/>
    /// </summary>
    private void OnKeybindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = true;
    }

    /// <summary>
    /// Raised when LMB is unpressed at <see cref="DragContainer"/>
    /// </summary>
    private void OnKeybindUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        => _draggin ? DragMode.None : base.GetDragModeFor(relativeMousePos);
    #endregion

    /// <summary>
    /// Selects a tech prototype and opens info panel
    /// </summary>
    /// <param name="proto">Tech proto</param>
    /// <param name="availability">Tech availability</param>
    public void SelectTech(TechnologyPrototype proto, ResearchAvailability availability)
    {
        InfoContainer.RemoveAllChildren();
        if (!_player.LocalEntity.HasValue)
            return;

        CurrentTech = proto.ID;
        foreach (var child in DragContainer.Children)
        {
            if (child is FancyResearchConsoleItem item)
                item.IsSelected = item.Prototype.ID == proto.ID;
        }

        var control = new FancyTechnologyInfoPanel(
            proto,
            _accessReader.IsAllowed(_player.LocalEntity.Value, Entity),
            availability,
            _sprite,
            SoftCapMultiplier);
        control.BuyAction += args => OnTechnologyCardPressed?.Invoke(args.ID);
        InfoContainer.AddChild(control);
    }

    /// <summary>
    /// Resets pan and zoom to the state the UI was first opened in
    /// </summary>
    public void Recenter()
    {
        _position = _initialViewPosition;
        _zoom = 1f;

        ApplyView();
    }

    public override void Close()
    {
        base.Close();

        DragContainer.ClearConnectionCache();
        DragContainer.RemoveAllChildren();
        InfoContainer.RemoveAllChildren();
        _gridPositions.Clear();
    }

    private sealed record ResearchTreeLayout(
        Dictionary<string, Vector2i> Positions,
        List<TreeHeaderLayout> Headers);

    private sealed record TreeHeaderLayout(
        string Text,
        Color Color,
        Vector2i Position,
        float Width,
        bool Major,
        string? Tooltip = null);

    /// <summary>
    /// Discipline/tier banner drawn behind the tree. Resizes itself with the view zoom.
    /// </summary>
    private sealed class TreeHeaderControl : PanelContainer
    {
        private const int BaseFontSize = 12;
        private const int MinFontSize = 7;

        private readonly Vector2 _baseSize;
        private readonly float _baseBorderThickness;
        private readonly Label _label;

        public TreeHeaderControl(TreeHeaderLayout header)
        {
            _baseSize = new Vector2(header.Width, header.Major ? 30 : 24);
            _baseBorderThickness = header.Major ? 2 : 1;

            SetSize = _baseSize;
            MouseFilter = header.Tooltip == null ? MouseFilterMode.Ignore : MouseFilterMode.Pass;
            ToolTip = header.Tooltip;
            TooltipDelay = 0.15f;
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = header.Color.WithAlpha(header.Major ? 0.24f : 0.13f),
                BorderColor = header.Color.WithAlpha(header.Major ? 0.9f : 0.55f),
                BorderThickness = new Thickness(_baseBorderThickness),
            };

            _label = new Label
            {
                Text = header.Text,
                FontColorOverride = header.Color,
                Margin = new Thickness(6, 2),
                ClipText = true,
                MouseFilter = MouseFilterMode.Ignore,
            };

            AddChild(_label);
        }

        public void SetZoom(float zoom, Func<int, Font> fontFactory)
        {
            SetSize = _baseSize * zoom;
            _label.Margin = new Thickness(6 * zoom, 2 * zoom);
            _label.FontOverride = fontFactory(
                Math.Max(MinFontSize, (int) MathF.Round(BaseFontSize * zoom)));

            if (PanelOverride is StyleBoxFlat flat)
                flat.BorderThickness = new Thickness(MathF.Max(1f, _baseBorderThickness * zoom));
        }
    }

}
